MODEL:
  BACKBONE_FILE: "./pretrain/res2net50.pth"
  SIZE_DIVISIBILITY: 32
  META_ARCHITECTURE: "EUVPS"
  LEN_CLIP_WINDOW: 6
  PER_LEN_CLIP_WINDOW: 3
  SHORT_PROC: True
  SHAPE_DIM: 256
  BACKBONE:
    MODEL: "res2net50"
    NAME: "build_res2net50"
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  IN_CHANNELS: [ 256, 512, 1024, 2048 ]
  QUERY_PROC_CHANNELS: [ 256, 512, 1024, 2048 ]
  SEM_SEG_HEAD:
    NAME: "euvps_sem_seg_head"
    IGNORE_VALUE: 255
    NUM_CLASSES: 1
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: [ "res2", "res3", "res4", "res5" ]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: [ "res4", "res5" ]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
    PROJECT_FEATURES: [ "res5" ]
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VitaMultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 128
    NUM_OBJECT_QUERIES: 200
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
  VITA:
    ENC_WINDOW_SIZE: 6
    SIM_WEIGHT: 0.5
    LAST_LAYER_NUM: 1
    NUM_OBJECT_QUERIES: 200
    HIDDEN_DIM: 256
    DEC_LAYERS: 2
DATASETS:
  TRAIN: ("SUN-SEG",)

DATALOADER:
  NUM_WORKERS: 8
INPUT:
  MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536, 1792)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MAX_SIZE_TRAIN: 4096
  CROP:
    ENABLED: False
    TYPE: "absolute"
    SIZE: (512, 512)
SOLVER:
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 1
  BASE_LR: 0.0001
  MAX_ITER: 30000
  WEIGHT_DECAY: 0.1
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
#    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.001
    NORM_TYPE: 2.0
  BIAS_LR_FACTOR: 1.
OUTPUT_DIR: './output/res2net50_sunseg'
DATA_DIR: "./SUN-SEG/TestEasyDataset/"
SAVE_DIR: "./output/res2net50_sunseg/vis/"
MODEL_PATH: "./output/res2net50_sunseg/model_final.pth"
